/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as InteriorDetailRouteImport } from './routes/interior-detail'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FullDetailRouteImport } from './routes/full-detail'
import { Route as ExteriorWashRouteImport } from './routes/exterior-wash'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'

const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorDetailRoute = InteriorDetailRouteImport.update({
  id: '/interior-detail',
  path: '/interior-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FullDetailRoute = FullDetailRouteImport.update({
  id: '/full-detail',
  path: '/full-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ExteriorWashRoute = ExteriorWashRouteImport.update({
  id: '/exterior-wash',
  path: '/exterior-wash',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/exterior-wash': typeof ExteriorWashRoute
  '/full-detail': typeof FullDetailRoute
  '/gallery': typeof GalleryRoute
  '/interior-detail': typeof InteriorDetailRoute
  '/quote': typeof QuoteRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/exterior-wash': typeof ExteriorWashRoute
  '/full-detail': typeof FullDetailRoute
  '/gallery': typeof GalleryRoute
  '/interior-detail': typeof InteriorDetailRoute
  '/quote': typeof QuoteRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/exterior-wash': typeof ExteriorWashRoute
  '/full-detail': typeof FullDetailRoute
  '/gallery': typeof GalleryRoute
  '/interior-detail': typeof InteriorDetailRoute
  '/quote': typeof QuoteRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/exterior-wash'
    | '/full-detail'
    | '/gallery'
    | '/interior-detail'
    | '/quote'
    | '/guides/$slug'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/exterior-wash'
    | '/full-detail'
    | '/gallery'
    | '/interior-detail'
    | '/quote'
    | '/guides/$slug'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/exterior-wash'
    | '/full-detail'
    | '/gallery'
    | '/interior-detail'
    | '/quote'
    | '/guides/$slug'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExteriorWashRoute: typeof ExteriorWashRoute
  FullDetailRoute: typeof FullDetailRoute
  GalleryRoute: typeof GalleryRoute
  InteriorDetailRoute: typeof InteriorDetailRoute
  QuoteRoute: typeof QuoteRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-detail': {
      id: '/interior-detail'
      path: '/interior-detail'
      fullPath: '/interior-detail'
      preLoaderRoute: typeof InteriorDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-detail': {
      id: '/full-detail'
      path: '/full-detail'
      fullPath: '/full-detail'
      preLoaderRoute: typeof FullDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exterior-wash': {
      id: '/exterior-wash'
      path: '/exterior-wash'
      fullPath: '/exterior-wash'
      preLoaderRoute: typeof ExteriorWashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExteriorWashRoute: ExteriorWashRoute,
  FullDetailRoute: FullDetailRoute,
  GalleryRoute: GalleryRoute,
  InteriorDetailRoute: InteriorDetailRoute,
  QuoteRoute: QuoteRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
